### ISSUE TITLE
Tarea 1.1. Historia y evolución de La Teoría de Autómatas y Lenguajes Formales

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#1]
Realizar un cuadro comparativo que describa los aportes de los principales investigadores que sustentaron la Teoría de Autómatas.

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 1.1
Buenas Tardes profesor le envió el link de mi [_repositorio_](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) para las tareas del semestre.
Link de la tarea:[**Tarea 1.1**](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/6482fe373cb93a5941c63b3ee36acf2d6086e6ce/Tema%201/1.1.%20Historia%20y%20evoluci%C3%B3n%20de%20La%20Teor%C3%ADa%20de%20Aut%C3%B3matas%20y%20Lenguajes%20Formales.md)
Atte. Martin Feria Vázquez NC 21200594

**Comment by GermanZL** [comment]
Buen día, le hago entrega de los links de mi repositorio así como de la tarea 1.1.
Link de tarea: [Tarea 1.1 - Zeron Lopez German Eduardo](https://github.com/GermanZL/automatas/blob/master/Tareas/Tarea%201.1.%20Historia%20y%20evoluci%C3%B3n%20de%20La%20Teor%C3%ADa%20de%20Aut%C3%B3matas%20y%20Lenguajes%20Formales.md)
Link del repositorio: [Repositorio](https://github.com/GermanZL/automatas.git)
Saludos.

**Comment by Josuerh20** [comment]
Buenas noches, le hago entrega de la tarea 1.1 y de repositorio
Link de tarea:
[Tarea 1.1 Josue Ramirez Hernandez](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas/Tarea%201.1.md)
Link de repositorio:
[Repositorio Josue Ramírez Hernández](https://github.com/Josuerh20/Lenguajes-Automatas-J.git)

**Comment by GabrielRoFe** [comment]
Buen día, le entrego el link de la tarea 1.1 y de mi repositorio:
[TAREA 1.1](https://github.com/GabrielRoFe/LenguajesYAutomatas/blob/8eb3b9cfa4f3ecfb9043b3d8f3e1c39f0a1a868d/cuadro%20comparativo.pdf)
[Repositorio](https://github.com/GabrielRoFe/LenguajesYAutomatas.git)

**Comment by GabrielRoFe** [comment]
Buen día, le dejo los links acerca de la tarea 1.1
Enlace de la tarea
[Tarea 1.1](https://github.com/GabrielRoFe/LenguajesYAutomatas/blob/d0648018b7cab30b49bbae6608406f3bd475f447/VeraRodr%C3%ADguezH%C3%A9ctorGabriel.pdf)
Enlace de repositorio
[Repositorio](https://github.com/GabrielRoFe/LenguajesYAutomatas.git
)

**Comment by UrielAhumada** [comment]
Buen día, entrego link de repositorio y tarea 1.1
Repositorio: https://github.com/UrielAhumada/Lenguajes_Automatas1
Tarea 1,1:https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema1/Tarea1.1.md

**Comment by RDGKing** [comment]
Buenas noches, profesor. 

Le envío el enlace de mi repositorio que estaré utilizando para las tareas del semestre: [**Repositorio**](https://github.com/RDGKing/Leng.-Y-Automatas-I.git) 

También le envío el enlace del apartado donde se encuentra la tarea: [**#Tarea 1.1**](https://github.com/RDGKing/Leng.-Y-Automatas-I/blob/main/Tema%201/21200581%20-%20Tarea%201.1.%20Historia%20y%20evoluci%C3%B3n%20de%20La%20Teor%C3%ADa%20de%20Aut%C3%B3matas%20y%20Lenguajes%20Formales.pdf)  

Agradezco mucho su atención.

**Comment by UrielAhumada** [comment]
Buen día, entrego link de repositorio y tarea 1.1
[Repositorio](https://github.com/UrielAhumada/Lenguajes_Automatas1)
[Tarea 1.1. Historia y evolución de La Teoría de Autómatas y Lenguajes Formales](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema1/Tarea1.1.md)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by DonovanFranco** [comment]
Buen noches ingeniero, hago entrega de la Actividad 1.1 y del enlace de mi repositorio
Enlace de repositorio:
[Repositorio](https://github.com/DonovanFranco/Lenguajes_Automatas_1)
Enlace de la Actividad 1.1:
[Tarea 1.1. Historia y evolución de La Teoría de Autómatas y  Lenguajes Formales](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades/Tarea%201.1.%20Historia%20y%20evoluci%C3%B3n%20de%20La%20Teor%C3%ADa%20de%20Aut%C3%B3matas%20y%20Lenguajes%20Formales.md)

Gracias por su atención, saludos

**Comment by Tesla9750** [comment]
Buenas noches ingeniero, esperando que cuente con una grata noche, anexo la evidencia de la actividad "Tarea 1.1. Historia y evolución de La Teoría de Autómatas y Lenguajes Formales", esperando que tenga una buena noche, me despido, Juan de Dios Benitez Nava, 21200582

Enlance del repositorio : [Repositorio](https://github.com/Tesla9750/Lenguajes_y_Automatas_1)
Enlance del Tarea 1.1 : [Tarea 1.1](https://github.com/Tesla9750/Lenguajes_y_Automatas_1/blob/7e1b66de89355603b27c9d68f1dad6127f4f49e0/Tema%201/Tarea_1_1_Historia_y_evolucion.md)

-NOTA: Actualice el link de la actividad debido a que realice cambios dentro de mi repositorio para ubicar mis archivos de manera mas ordenada_

**Comment by Jhonny-Gonzalez** [comment]
Buenas noches, hago entrega de la tarea 1.1
[Repositorio](https://github.com/Jhonny-Gonzalez/repositorioNuevo.git)
[Actividad 1.1](https://github.com/Jhonny-Gonzalez/repositorioNuevo/blob/main/U1/Tarea%201.1.pdf)

**Comment by Marly-R** [comment]
Buenas noches inge, le hago entrega de la Actividad 1.1 y del enlace de mi repositorio

Enlace de repositorio: https://github.com/Marly-R/RepoNuevo/tree/master
Enlace de la Actividad 1.1:  https://github.com/Marly-R/RepoNuevo/blob/master/Tema1/Tema1.1.md

Nombre: Marly Galarza Acosta 22201111

**Comment by Marly-R** [comment]
Buenas noches ingeniero, hago entrega de la Actividad 1.1 y del enlace de mi repositorio

- Enlace de repositorio: [Repositorio](https://github.com/Marly-R/RepoNuevo/tree/master)
- Enlace de la Actividad 1.1: [Atividad 1.1](https://github.com/Marly-R/RepoNuevo/blob/master/Tema1/Tema1.1.md)

Nombre: Marly Galarza Acosta 22201111

**Comment by AriMC432** [comment]
Buenas noches hago entrega de la actividad 1.1

Enlace de repositorio https://github.com/AriMC432/Repts
Enlace de actividad https://github.com/AriMC432/Repts/tree/1b3b640c4e2b0476480d5e72ae4d7d145a6b11cc/Tareas

**Comment by DanielFloresBautista** [comment]
Hola, buenas noches. 
Hago entrega de mis actividades del [repositorio ](https://github.com/DanielFloresBautista/Tarea1.1/blob/main/Repositorio.md) y la [tarea1.1](https://github.com/DanielFloresBautista/Tarea1.1/blob/main/Nuevo.md)
Nombre: Flores Bautista Daniel 
NC: 21200595

**Comment by MielFigueroa** [comment]
Buenas Tardes anexo entrega de la Tarea del Tema 1.1
Enlace de actividad: https://github.com/MielFigueroa/Miel/blob/master/LineaDeTiempo.pdf
Nombre: Melanie Dominguez Figueroa
No. Control: 22200181

**Comment by MaRqKiTe** [comment]
Buenas tardes hago entrega de la evidencia 
Enlace del repositorio: [https://github.com/MaRqKiTe/repe/tree/master](url)
Enlace de la tarea: [https://github.com/MaRqKiTe/repe/tree/master/Tarea%201.1](url)
Nombre: Marco Antonio Lara López
No: 22200191

**Comment by sergiotorr** [comment]
Buenas tardes profesor, anexo el enlace de la tarea del tema 1.1: [Tarea 1.1](https://github.com/sergiotorr/RepSergio/blob/main/Cuadro%20Comparativo%2021200636.pdf)
Nombre: Torres Martinez Sergio Enrique
No. Control: 21200636

**Comment by MaRqKiTe** [comment]
Buenas tardes, anexo la evidencia de la actividad 
Enlace del repositorio: [Repositorio](https://github.com/MaRqKiTe/repe)
Enlace de la actividad: [Tarea 1.1](https://github.com/MaRqKiTe/repe/tree/master/Tarea%201.1)
Nombre: Marco Antonio Lara López 
No. 22200191

**Comment by jesus-borja** [comment]
Buenas noches, profesor, anexo el enlace al [repositorio ](https://github.com/jesus-borja/LengAutomatasI)que usaré para este curso.
Así mismo anexo el enlace de la [Tarea 1.1](https://github.com/jesus-borja/LengAutomatasI/blob/main/Tema%201/Tarea%201.1%20Historia%20y%20evoluci%C3%B3n%20de%20la%20Teor%C3%ADa%20de%20Aut%C3%B3matas%20y%20Lenguajes%20Formales.pdf).

> Jesús Borja Hernández
> No. de Control: 21200584

**Comment by lHatHamy** [comment]
Buenas noches profesor. Anexo mi repositorio de git junto con el enlace de mi tarea 1.1 y mis datos de estudiante. De antemano le agradezco su atención

Repositorio: [Lenguajes y automatas](https://github.com/lHatHamy/lye/tree/main)
Actividad: [Tarea 1.1](https://github.com/lHatHamy/lye/blob/main/Tema1/Tarea1.1.pdf)

> Uriel Alberto Serrano González
>N. De Control: 21200630

**Comment by ClaudiaHernandez03** [comment]
Buenas noches Ingeniero. Anexo el enlace de mi repositorio y el enlace de mi tarea.
Enlace de repositorio [Repositorio](gh repo clone ClaudiaHernandez03/automatas)
Tarea 1.1: [](https://github.com/ClaudiaHernandez03/automatas/blob/177ab5d2b1b28df90dcc00af963465c8b0f2f35c/Tema.1/Tarea%201.1.%20Historia%20y%20evoluci%C3%B3n%20de%20La%20Teor%C3%ADa%20de%20Aut%C3%B3matas.md)

**Comment by ClaudiaHernandez03** [comment]
Buenas noches ingeniero, anexo mi enlace de mi repositorio y mi tarea:

- [ Repositorio ](https://github.com/ClaudiaHernandez03/automatas.git)


- [ Tarea1.1 ](https://github.com/ClaudiaHernandez03/automatas/blob/177ab5d2b1b28df90dcc00af963465c8b0f2f35c/Tema.1/Tarea%201.1.%20Historia%20y%20evoluci%C3%B3n%20de%20La%20Teor%C3%ADa%20de%20Aut%C3%B3matas.md)

**Comment by GavicGH** [comment]
Buenas noches profesor, hago entrega de el repositorio y la tarea 1.1

 - [Repositorio](https://github.com/VGabriel31/Lenguajes_Automatas_1)
 - [Tarea 1.1](https://github.com/VGabriel31/Lenguajes_Automatas_1/blob/main/Tarea_1.1.md)
 

> Gutierrez Hernandez V. Gabriel
> 21200605

**Comment by Itzel-Paola-Garcia** [comment]
Buenas noches le mando el link de mi repositorio y de mi tarea

- [Repositorio](https://github.com/Itzel-Paola-Garcia/LeguajesAutomatas.git)
- [Tarea 1.1](https://github.com/Itzel-Paola-Garcia/LeguajesAutomatas/blob/main/Historia%20y%20evoluci%C3%B3n%20de%20La%20Teor%C3%ADa%20%20de%20Aut%C3%B3matas%20y%20Lenguajes%20Formales.pdf)

**Comment by Marr1731** [comment]
Buenas noches Profesor comparto mi link de mi repositorio
1. [Repositorio](https://github.com/Marr1731/ActividadesLenguajesAutonomas)
 
También anexo el enlace de mi tarea
 2. [Tarea 1.1 ](https://github.com/Marr1731/ActividadesLenguajesAutonomas/blob/main/Tarea1.1.md)

Mariana Mendoza Gutiérrez
N.Control : 21200615

**Comment by JohannaMontana** [comment]
Buenas noches profesor, le envío la actividad propuesta para el día de hoy, para su posterior evaluación

> [Tarea 1.1](https://github.com/JohannaMontana/Lenguajes-Automatas-I/tree/f25d755fcbf8cc2c2256303f66132b4027d3184c/Tema%201 )

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._

**Comment by Reyes-Hernandez-Reyes** [comment]
Buenas Noches profesor le adjunto mi:
[Repositorio](https://github.com/Reyes-Hernandez-Reyes/Repositorio)
[Tarea 1.1](https://github.com/Reyes-Hernandez-Reyes/Tarea-1.1) 
Hernandez Reyes Reyes
N.Control: 21200608

**Comment by CariciasDealer** [comment]
Muy buenas noches, ingeniero. Adjunto el enlace a mi repositorio [repositorio](https://github.com/CariciasDealer/Lenguaje-y-Automatas) y a la [Actividad 1.1](https://github.com/CariciasDealer/Lenguaje-y-Automatas/blob/main/1.1.%20Historia%20y%20evolución%20de%20La%20Teoría%20de%20Autómatas%20y%20Lenguajes%20Formales.md)

Alumno: Taboada Hernandez Erwin Omar
No. Control: 21200631

¡Saludos!

**Comment by diegoquintos** [comment]
Buenas noches, aquí están los enlaces de 
[Tarea 1.1](https://github.com/diegoquintos/LengAutomatas/blob/main/tarea1.1.md)
[Repositorio](https://github.com/diegoquintos/LengAutomatas)
Quintos Cabeza Diego
N.C 21200625

**Comment by abisaiCM** [comment]
hola, aqui esta el enlace del repositorio https://github.com/abisaiCM/lenguajesYAutomatas.git
link de la tarea https://github.com/abisaiCM/lenguajesYAutomatas/blob/main/1_1%20CUADRO%20COMPARATIVO.pdf
