### ISSUE TITLE
Tarea 3.2 Caso practico Automata Finito

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#10]
Investigar caso  de uso real de un autómata finito cual es su aplicación e implementación del mismo.

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 3.2 Caso practico Autómata Finito
Buenas Tardes profesor le envió el link de mi [Repositorio](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) y mi trabajo.
Link de la tarea: [Tarea 3.2](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/7bc6c2e064d7b7ef693a9fca08656c97684fee48/Tema%203/3.2%20Caso%20Practico%20Automata%20Finito.md)
Atte. Martin Feria Vázquez NC 21200594

**Comment by AdrianSanBad** [comment]
🚀

**Comment by Josuerh20** [comment]
Buenas tares le hago entrega de la tarea 3.2
Link de tarea: [Tarea 3.2](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas%20Tema%203/Tarea%203.2.md)

Ramírez Hernández Josue NC 21200990

**Comment by GermanZL** [comment]
Buenas tares le hago entrega de la tarea 3.2
Link de tarea: [Tarea 3.2](https://github.com/GermanZL/automatas/blob/master/Tareas/Tarea%203.2.md)

Zeron Lopez German Eduardo - 21200642

**Comment by JohannaMontana** [comment]
Buenos días profesor, le envío la actividad propuesta el día de hoy, para su posterior evaluación

[Tarea 3.2](https://github.com/JohannaMontana/Lenguajes-Automatas-I/blob/main/Tema%203/3.2_Automata%20finito.pdf)

Morales Mateos Johanna
Alumna de ingeniería en sistemas computacionales.
Matrícula: 21200619
Instituto Tecnológico de Pachuca.

**Comment by JohannaMontana** [comment]
Buenos días profesor, le envío la actividad propuesta el día de hoy, para su posterior evaluación

> [Tarea 3.2](https://github.com/JohannaMontana/Lenguajes-Automatas-I/blob/main/Tema%203/3.2_Automata%20finito.pdf)

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._

**Comment by UrielAhumada** [comment]
Buen día, entrego tarea 3.2
[Tarea 3.2. Caso practico Automata Finito](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema3/Tarea3.2.md)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by DonovanFranco** [comment]
Buenas noches ingeniero, envió evidencia de la Actividad 3.2
- [Tarea 3.2 Automata Finito](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades%20Tema%203/Tarea%203.2.md)

Por su atención, muchas gracias.
- ***Donovan Urazh Franco Flores***
- **21200596**

**Comment by sergiotorr** [comment]
Buenas noches profesor, entrego tarea [Tarea 3.2](https://github.com/sergiotorr/RepSergio/blob/main/Tarea%203.2%20Caso%20practico%20Automata%20Finito%2021200636.pdf)

Alumno: Torres Martínez Sergio Enrique
No. Boleta: 21200636

**Comment by AlfredoVelazquez** [comment]
Buenas noches Ing. Hago entrega de la actividad correspondiente
[Tarea 3.2 Casos de Uso](https://github.com/AlfredoVelazquez/AutoNuevo/blob/main/3.2%20Investigacion.pdf)

**Comment by Marly-R** [comment]
Buenas noches Profe le envió la Actividad 3.2

[Tarea 3.2](https://github.com/Marly-R/RepoNuevo/blob/master/Tema3/Tarea%203.2.pdf)


Marly Galarza Acosta - 22201111

**Comment by GavicGH** [comment]
Buenas noches profesor, hago la entrega de la [Tarea 3.2](https://github.com/VGabriel31/Lenguajes_Automatas_1/blob/main/Tarea%203.2.md)
>21200605 
>Gutierrez Hernandez Victor Gabriel

**Comment by Marr1731** [comment]
Buenas noches Profe le envió la Actividad 3.2

[Tarea 3.2](https://github.com/Marr1731/ActividadesLenguajesAutonomas/blob/main/Auttonomas%20Finitos.pdf)

Mariana Mendoza Gutierrez- 21200615

**Comment by MielFigueroa** [comment]
Buenas noches envió Tarea 3.2
Melanie Dominguez Figueroa   No. Control: 22200181
[Tarea 3.2](https://github.com/MielFigueroa/Miel/blob/master/TAREA%203.2%20CASOS%20DE%20USO%20AUT%C3%93MATA%20FINITO)

**Comment by diegoquintos** [comment]
Buenas noches envío la [Tarea 3.2](https://github.com/diegoquintos/LengAutomatas/blob/main/Tarea3.2.md)
Quintos Cabeza Diego 
NC:21200625

**Comment by ClaudiaHernandez03** [comment]
Buenas Tardes, entrego tarea 3.2
[Tarea 3.2. Caso practico Autómata Finito](https://github.com/ClaudiaHernandez03/automatas/blob/main/Tema%203/tarea%203.2.md)
Claudia América Hernández Jiménez
N° Control: 21200607

**Comment by belen1909** [comment]
[Investigacion](https://github.com/belen1909/belenautomatas/blob/main/ACT%20INVESTIGACION%20.pdf)

**Comment by DanielFloresBautista** [comment]
Envío la [Tarea 3.2](https://github.com/DanielFloresBautista/NuevoRepositorio/blob/main/aut%C3%B3mata_finito.md)
Flores Buatista Daniel
NC:21200595

**Comment by CariciasDealer** [comment]
Buenas tardes, ingeniero. Le hago entrega de mi [actividad 3.2](https://github.com/CariciasDealer/Lenguaje-y-Automatas/blob/main/Tema%203/21200631%20-%20Tarea%203.2%20Caso%20practico%20Automata%20Finito.pdf), que tenga un excelente dia

Taboada Hernandez Erwin Omar
No. Control :21200631
