### ISSUE TITLE
4.1 Tabla de Tokens para el proyecto de Analizador Léxico

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#11]
**Definición del lenguaje:** Antes de empezar, necesitas tener una comprensión clara del lenguaje que tu analizador léxico va a analizar. Define las reglas de tu lenguaje, como palabras clave, operadores, símbolos especiales, comentarios, etc.

**Especificación de tokens:** Define los tokens o símbolos que el analizador léxico va a reconocer en tu lenguaje. Estos pueden incluir palabras clave, identificadores, números, operadores, símbolos especiales, etc.

Definir patrones regulares que describan la estructura de cada tipo de token.

Entregable Tabla de Tokens.

**Comment by MartinFV-001** [comment]
¡¡¡Listo, ya en repositorio!!!
![Imagen](https://i.pinimg.com/originals/02/40/39/024039c80452f5313fef3b8bc6380a4c.gif)

**Comment by AdrianSanBad** [comment]
entregados en mi repositorio carpeta entrega de tareas

**Comment by UrielAhumada** [comment]
Buen día, entrego Tabla de Tokens para el proyecto de Analizador Léxico
[4.1 Tabla de Tokens para el proyecto de Analizador Léxico](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema4/4.1%20Tabla%20de%20Tokens%20para%20el%20proyecto%20de%20Analizador%20L%C3%A9xico%20.pdf)
