### ISSUE TITLE
4.3 Proyecto Analizador Léxico

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#13]
**1. Definición de tokens:** Utilizar la tabla de tokens ya definida que debe reconocer el analizador léxico. Por ejemplo, pueden incluir palabras clave del lenguaje, identificadores, números, operadores, símbolos especiales, etc.

**2. Expresiones regulares:** Utilizar las expresiones regulares definidas en su documentación para definir las reglas de coincidencia de cada token. Por ejemplo, una expresión regular para identificar números enteros podría ser \d+, que coincide con una o más ocurrencias de dígitos.

**3. Manejo de comentarios:** Definir cómo manejar los comentarios en el código fuente. Por ejemplo, pueden optar por ignorar los comentarios completamente o incluirlos como un token separado para su posterior procesamiento.

**4. Prioridad de coincidencia:** Resolver conflictos cuando una misma secuencia de caracteres puede corresponder a múltiples tokens. Por ejemplo, puedes establecer una prioridad de coincidencia donde se prioricen los tokens más largos sobre los más cortos, o definir reglas específicas para manejar casos ambiguos.

**5. Acciones asociadas a los tokens:** Asociar acciones a cada token reconocido. Estas acciones pueden incluir la asignación de un tipo de token, la recopilación de información adicional (como el valor de un número), la generación de mensajes de error, etc.

**6. Manejo de errores:** Especificar el manejo de los errores de análisis léxico, como caracteres desconocidos o secuencias inválidas. Pueden optar por generar un mensaje de error y continuar el análisis, o detener el análisis y reportar un error fatal.

**8. Documentación:** Documentar su código, incluyendo comentarios claros que expliquen el propósito de cada parte del analizador léxico y cómo se deben utilizar las diferentes funciones o clases.

**Comment by MartinFV-001** [comment]
Listo en Repo 🚀🚀😎
https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/1440c228a07a7da2c0d9b3410522f4db1e7d7433/Tema%204/readme.md

**Comment by Reyes-Hernandez-Reyes** [comment]
Subido al repositorio

**Comment by UrielAhumada** [comment]
Buen dia, entrego Proyecto Analizador Lexico
[Analizador Léxico](https://urielahumada.github.io/pagina-web-analizador-lexico/)
