### ISSUE TITLE
5.1 Requerimiento de la Gramática

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#14]
**Descripción detallada de la gramática del lenguaje**

**Objetivo:** Proveer una descripción clara y completa de la gramática del lenguaje que se va a analizar, especificando todas las producciones y reglas necesarias para la correcta implementación del analizador sintáctico.

Contenidos de la Descripción de la Gramática

**1. Introducción**

Breve descripción del lenguaje de programación o el subconjunto del lenguaje que se va a analizar.

Propósito del analizador sintáctico y cómo encaja dentro del proceso de compilación o interpretación del lenguaje.

**2. Símbolos Terminales**

Lista completa de los símbolos terminales del lenguaje, que incluyen:

- Palabras clave (e.g., if, else, while).
- Operadores (e.g., +, -, *, /).
- Delimitadores (e.g., (, ), {, }, ;).
- Literales (e.g., números, cadenas).
- Identificadores (variables, nombres de funciones).

Ejemplo:

Terminales:
- Palabras clave: if, else, while, return
- Operadores: +, -, *, /
- Delimitadores: (, ), {, }, ;
- Literales: números, cadenas
- Identificadores: variables, nombres de funciones

**3. Símbolos No Terminales**

Definir los símbolos no terminales que representan categorías o estructuras sintácticas del lenguaje.

Ejemplo:

No Terminales:
- E (Expresión)
- T (Término)
- F (Factor)
- Stmt (Declaración)
- StmtList (Lista de Declaraciones)

**4. Producciones y Reglas**

Especificar todas las producciones (reglas) que describen cómo los símbolos no terminales se descomponen en otros no terminales y terminales.

Cada producción debe ser clara y seguir el formato estándar de una gramática libre de contexto (CFG).

Ejemplo:

Producciones:
1. S -> StmtList
2. StmtList -> Stmt StmtList | ε
3. Stmt -> id = Expr ;
4. Expr -> Expr + Term | Expr - Term | Term
5. Term -> Term * Factor | Term / Factor | Factor
6. Factor -> ( Expr ) | id | num

**5. Símbolo Inicial**

Indicar cuál es el símbolo inicial de la gramática, desde donde se empiezan las derivaciones.

Ejemplo:

Símbolo Inicial:
- S (Programa)

**6. Precedencia y Asociatividad (si aplica)**

Definir las reglas de precedencia y asociatividad para operadores, si la gramática incluye expresiones aritméticas o lógicas.

Ejemplo:

Precedencia y Asociatividad:
- Operadores multiplicativos (*, /): mayor precedencia, asociatividad izquierda.
- Operadores aditivos (+, -): menor precedencia, asociatividad izquierda.

**7. Comentarios y Anotaciones**

Incluir comentarios y explicaciones adicionales para clarificar las reglas y producciones, especialmente en casos complejos o no triviales.

Ejemplo:

Comentarios:
- `StmtList -> Stmt StmtList | ε`: Permite una lista de declaraciones, incluyendo la lista vacía.
- `Factor -> ( Expr ) | id | num`: Los factores pueden ser expresiones entre paréntesis, identificadores o números.

**Comment by AlfredoVelazquez** [comment]
Adjunto el archivo de la actividad 5.1

[Requeimientos de la Gramática](https://github.com/AlfredoVelazquez/AutoNuevo/blob/main/GRAM%C3%81TICA%20DEL%20LENGUAJE.pdf)

**Comment by MartinFV-001** [comment]
Ya en repo 🚀🚀🚀

**Comment by MielFigueroa** [comment]
Buen dia envio tarea correspondiente [TAREA 5.1](https://github.com/MielFigueroa/Miel/blob/master/LENGUAJE%20SINTACTICO.pdf)

**Comment by UrielAhumada** [comment]
Buen día, entrego 5.1
[5.1 Requerimiento de la Gramática](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema5/5.1%20Requerimiento%20de%20la%20Gram%C3%A1tica.pdf)
