### ISSUE TITLE
5.2. Desarrollo de un Analizador Sintáctico para un Lenguaje de Programación Simple

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#15]
**Requisitos:**

**Gramática:** Describir claramente la gramática del lenguaje a analizar, incluyendo todas las producciones y reglas.

**Implementación:**

Implementar un analizador sintáctico que procese correctamente las entradas válidas y reporte errores en las entradas inválidas. Esto después de que haya pasado las pruebas del analizador léxico elaborado e implementado en el Tema anterior.

Utilizar técnicas de análisis descendente predictivo o ascendente según corresponda.

**Eficiencia:** El analizador debe ser capaz de manejar entradas de tamaño significativo con un rendimiento aceptable.

**Manejo de Errores:** Proporcionar mensajes de error claros y específicos que indiquen la naturaleza y ubicación del error.

**Documentación:** Incluir documentación detallada del diseño y uso del analizador, así como casos de prueba que cubran todos los aspectos de la gramática.

**Pruebas:** Incluir un conjunto de pruebas que validen la funcionalidad del analizador.

**Interfaz:** Proveer una interfaz de línea de comandos para la ejecución del analizador.

**Comment by AlfredoVelazquez** [comment]
Buenas noches Ing. Le adjunto el link del repositorio creado para la entrega de los proyectos, Analizador 
lexico y sintactico.....
Graciasss

[REPOSITORIO DE PROYECTOS](https://github.com/AlfredoVelazquez/Automatas_AnalizadorSintactico)

**Comment by MielFigueroa** [comment]
Buenas noches envió el link del repositorio en donde se encuentran los proyectos del lenguaje sintáctico y léxico
[PROYECTO-AUTOMATAS](https://github.com/MielFigueroa/PROYECTO-AUTOMATAS)

**Comment by UrielAhumada** [comment]
Buen dia, entrego analizador sintactico
[5.2. Desarrollo de un Analizador Sintáctico para un Lenguaje de Programación Simple](https://github.com/UrielAhumada/Lenguajes_Automatas1/tree/main/Tema5/5.2.%20Desarrollo%20de%20un%20Analizador%20Sint%C3%A1ctico%20para%20un%20Lenguaje%20de%20Programaci%C3%B3n%20Simple)
