### ISSUE TITLE
6.1 Mapa Conceptual de Máquinas de Turing

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#16]
Creación de un mapa conceptual detallado sobre las máquinas de Turing. 

Que el mapa incluya los siguientes aspectos:

**Componentes Básicos:** Tinta, cabezal, estados, alfabeto.

**Funcionamiento:** Cómo se mueve el cabezal, cómo se leen y escriben símbolos.

**Tipos de Máquinas de Turing:** Determinísticas, no determinísticas, universales.

**Importancia:** En la teoría de la computación, problemas que resuelve, limitaciones, impacto en la teoría de la computación.

**Ejemplos:** Ejemplos de problemas que se pueden resolver con una máquina de Turing.

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 6.1 Mapa Conceptual de Máquinas de Turing
Buenas Tardes profesor le envió el link de mi [Repositorio](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) y mi trabajo.
Link de la tarea:[Tarea 6.1](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/b7c1d318444d388ddf9593178fdfbd998c68a5bf/Tema%206/6.1%20Mapa%20Conceptual%20de%20M%C3%A1quinas%20de%20Turing.md)
Atte. Martin Feria Vázquez NC 21200594

**Comment by MielFigueroa** [comment]
Buenas Tares envio [TAREA 6.1](https://github.com/MielFigueroa/Miel/blob/master/TAREA%206.1%20MAQUINAS%20DE%20TURING.pdf)
Melanie Dominguez Figueroa No. Control: 22200181

**Comment by Josuerh20** [comment]
Buenas tardes hago entrega de la Tarea 6.1 Mapa Conceptual de Máquinas de Turing 
Link de tarea : [Tarea 6.1](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas%20tema%206/6.1%20Mapa%20conceptual%20de%20Turing%20Josue.pdf)
Josue Ramírez Hernández - 21200990

**Comment by Jhonny-Gonzalez** [comment]
Buenas noches, hago entrega de la tarea 6.1:
[Tarea 6.1: Mapa Conceptual de Máquinas de Turing](https://github.com/Jhonny-Gonzalez/repositorioNuevo/blob/main/U6/M%C3%A1quinas%20de%20Turing.pdf)
Ochoa Gonzalez Jonathan Emir
N.Control: 21200988

**Comment by UrielAhumada** [comment]
Buen día, entrego tarea 6.1
[6.1 Mapa Conceptual de Máquinas de Turing](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema6/Tarea6.1.md)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by DonovanFranco** [comment]
Buenas noches ingeniero, envió evidencia de la Actividad 6.1
- [Tarea 6.1](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades%20Tema%206/Tarea%206.1.md)

Por su atención, muchas gracias.
- ***Donovan Urazh Franco Flores***
- **21200596**

**Comment by sergiotorr** [comment]
Buenas tardes profesor hago entrega de la tarea [6.1 Mapa Conceptual de Máquinas de Turing](https://github.com/sergiotorr/RepSergio/blob/main/6.1%20Mapa%20Conceptual%20de%20M%C3%A1quinas%20de%20Turing.pdf)
Torres Martínez Sergio Enrique
No. Boleta: 21200636

**Comment by ClaudiaHernandez03** [comment]
Buenas Tardes ingeniero, le entrego la evidencia de la Actividad 6.1

- [Tarea 6.1](https://github.com/ClaudiaHernandez03/automatas/blob/main/Tema%206/Tarea%206.1.md)


**_Att: Claudia América Hernández Jiménez_**
**21200607**

**Comment by GermanZL** [comment]
Buenas tardes hago entrega de la Tarea 6.1 Mapa Conceptual de Máquinas de Turing
Link de tarea : [Tarea 6.1](https://github.com/GermanZL/automatas/blob/master/Tareas/Mapa%20Conceptual%20-%20Maquinas%20de%20Turing.pdf)
Zeron Lopez German Eduarod - 21200642

**Comment by lHatHamy** [comment]
**Buenas noches profesor**
Hago la entrega del enlace de mi evidencia sobre la [Tarea 6.1](https://github.com/lHatHamy/lye/blob/main/Tema6/Tarea6.1.pdf)

Sin mas que agregar por el momento, le deseo una bonita noche.

> Uriel Alberto Serrano González | 21200630

**Comment by DanielFloresBautista** [comment]
Buenas tardes hago entrega de la Tarea 6.1 Mapa Conceptual de Máquinas de Turing
Link de tarea : [Tarea 6.1](https://github.com/DanielFloresBautista/Unidad-6/blob/main/Mapa%20Conceptual%20de%20M%C3%A1quinas%20de%20Turing.pdf)
Flores Bautista Daniel 21200595

**Comment by Marr1731** [comment]
Buenas noches profesor comparto con usted la Tarea 6.1 
Link de tarea : [Tarea 6.1](https://github.com/Marr1731/ActividadesLenguajesAutonomas/blob/main/6.1%20Mapa%20Conceptual%20de%20M%C3%A1quinas%20de%20Turing.md)
Mendoza Gutierrez Mariana 21200615

**Comment by AdrianSanBad** [comment]
🚀

**Comment by AlfredoVelazquez** [comment]
Hago entrega de la actividad correspondiente.
[MAQUINA DE TURING](https://github.com/AlfredoVelazquez/AutoNuevo/blob/main/Mapa_Maquinas%20de%20Turing.pdf)

**Comment by Marly-R** [comment]
Buenas noches profesor le hago entrega de mi [tarea 6.1](https://github.com/Marly-R/RepoNuevo/blob/master/Tema6/Mapa%20conceptial%20Maquinas%20de%20Turing.pdf)

Alumna: Marly Galarza Acosta 
No. Control: 22201111

**Comment by Reyes-Hernandez-Reyes** [comment]
Buenas noches Inge le hago entrega de la [Tarea 6.1](https://github.com/Reyes-Hernandez-Reyes/Tareas-Tema-6/blob/main/Tarea%206.1.pdf)
Alumno: Hernandez Reyes Reyes
No. Control: 21200608

**Comment by GavicGH** [comment]
Buenas noches hago entrega de la [Tarea 6.1](https://github.com/VGabriel31/Lenguajes_Automatas_1/blob/main/Tarea%206.1.pdf)
Alumno: Gutierrez Hernandez Victor Gabriel
No. Control: 21200605

**Comment by CariciasDealer** [comment]
Buenas noches, ingeniero. Le hago entrega de la [actividad 6.1](https://github.com/CariciasDealer/Lenguaje-y-Automatas/blob/main/Tema%206/21200631%20-%206.1%20Mapa%20Conceptual%20de%20Máquinas%20de%20Turing.pdf), quedo al pendiente. 

Que tenga un buen fin de semana. 

Taboada Hernandez Erwin Omar
No. Control: 21200631

**Comment by CariciasDealer** [comment]
> Buenas noches, ingeniero. Le hago entrega de la [actividad 6.1](https://github.com/CariciasDealer/Lenguaje-y-Automatas/blob/main/Tema%206/21200631%20-%206.1%20Mapa%20Conceptual%20de%20M%C3%A1quinas%20de%20Turing.pdf), quedo al pendiente.
> 
> Que tenga un buen fin de semana.

Taboada Hernandez Erwin Omar
No. Control: 21200631

**Comment by Tesla9750** [comment]
##   Mapa Conceptual de Máquinas de Turing  #16

Buenas días ingeniero,

Adjunto el enlace al documento donde he completado la [#Tarea 6.1 ](https://github.com/Tesla9750/Lenguajes_y_Automatas_1/blob/ca415dfc692b0388858bcec288e793b9b8f9a08b/Tema%206/m%C3%A1quinas%20de%20Turing.pdf)

Esperando que cuente con un grato día, me despido. 

Saludos,

*Benitez Nava Juan de Dios
Número de control: 21200582
Instituto Tecnológico de Pachuca*

**Comment by diegoquintos** [comment]
Buenas noches, adjunto mi [Tarea 6.1](https://github.com/diegoquintos/LengAutomatas/blob/main/MAPAS%20DE%20TURING.pdf)

_Quintos Cabeza Diego-21200625_

**Comment by belen1909** [comment]
Adjunto mi tarea [tarea 6.1](https://github.com/belen1909/belenautomatas/blob/main/M%C3%A1quinas%20de%20Turing.pdfl)

**Comment by JohannaMontana** [comment]
Buenos días profesor, le envío la actividad propuesta el día de hoy, para su posterior evaluación

> [Tarea 6.1](https://github.com/JohannaMontana/Lenguajes-Automatas-I/blob/main/Tema%206/6.1_Turing_21200619_.pdf)

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._
