### ISSUE TITLE
6.2 Comentarios película "The Imitation Game"

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#17]
Me gustaría me compartan sus comentarios o resumen sobre la película "The Imitation Game" (titulada "Código Enigma" ), que narra la vida y el trabajo de Alan Turing durante la Segunda Guerra Mundial.

Por favor, incluyan los siguientes puntos en el comentario o resumen:

**Sinopsis general de la película:** Una breve descripción de la trama principal.

**Descripción de los personajes principales:** En especial, Alan Turing y su papel en la historia.

**Aspectos históricos relevantes:** La importancia del trabajo de Turing en la descodificación de Enigma y su impacto en la guerra.

**Temas y mensajes principales:** Los temas tratados en la película, como la inteligencia, la guerra, la moralidad y la discriminación.

**Opinión crítica:** Comentarios sobre la calidad de la película, actuaciones, dirección y precisión histórica.

**Importancia de Alan Turing:** Su legado en el campo de la computación y su reconocimiento posterior.

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 6.2 Comentarios película "The Imitation Game"
Buenas Tardes profesor le envió el link de mi [Repositorio](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) y mi trabajo.
Link de la tarea: [Tarea 6.2](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/6abc782f304766490b1db17ae381f0cbd9c90ecf/Tema%206/6.2%20Comentarios%20pel%C3%ADcula%20%22The%20Imitation%20Game%22%20.md)
Atte. Martin Feria Vázquez NC 21200594

**Comment by MaRqKiTe** [comment]
Entrega de la [Tarea 6.2](https://github.com/MaRqKiTe/repe/blob/master/Tema%206/sipnosis.pdf) Maquinas de turing 

Lara López Marco Antonio No. Control: 22200191

**Comment by MielFigueroa** [comment]
Buenas Tardes hago entrega de la [TAREA 6.2](https://github.com/MielFigueroa/Miel/blob/master/TAREA%206.2.pdf)

Melanie Dominguez Figueroa No. Control: 22200181

**Comment by Josuerh20** [comment]
Buenas tardes hago entrega de la Tarea 6.2 Comentarios película "The Imitation Game"
Link de tarea : [Tarea 6.2](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas%20tema%206/6.2%20Comentarios%20pel%C3%ADcula%20The%20Imitation%20Game%20.pdf)
Josue Ramírez Hernández - 21200990

**Comment by UrielAhumada** [comment]
Buen día, entrego tarea 6.2
[Comentarios película "The Imitation Game"](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema6/Tarea6.2.md)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by GermanZL** [comment]
Buenas tardes hago entrega de la Tarea 6.2 Comentarios película "The Imitation Game"
Link de tarea : [Tarea 6.2](https://github.com/GermanZL/automatas/blob/master/Tareas/Comentarios%20pel%C3%ADcula.pdf)
Zeron Lopez German Eduardo - 21200642

**Comment by Reyes-Hernandez-Reyes** [comment]
Buenas dias Inge le hago entrega de la [Tarea 6.2](https://github.com/Reyes-Hernandez-Reyes/Tareas-Tema-6/blob/main/Tarea%206.2.pdf)
Alumno: Hernandez Reyes Reyes
No. Control: 21200608

**Comment by Marr1731** [comment]
Buenas tardes comparto con usted la  [Tarea 6.2](https://github.com/Marr1731/ActividadesLenguajesAutonomas/blob/main/6.2%20Comentarios%20pel%C3%ADcula%20%20%22The%20Imitation%20Game%22.md)

Mendoza Gutierrez Mariana - 21200615

**Comment by GavicGH** [comment]
Buenas tardes hago entrega de la Tarea 6.2 Comentarios película "The Imitation Game"
Link de tarea : [Tarea 6.2](https://github.com/VGabriel31/Lenguajes_Automatas_1/blob/main/Tarea%206.2.md)
Gutierrez Hernandez Victor Gabriel - 21200605

**Comment by DanielFloresBautista** [comment]
Buenas tardes hago entrega de la Tarea 6.2
Link de tarea : [Tarea 6.2](https://github.com/DanielFloresBautista/Unidad-6/blob/main/Codigo_enigma.md)
Flores Bautista Daniel - 21200595

**Comment by AdrianSanBad** [comment]
🚀

**Comment by belen1909** [comment]
Hago entrega de mi tarea 
Belen Barraza Islas 20200181
[comentario 6.2](https://github.com/belen1909/belenautomatas/blob/main/COMENTARIO%20DE%20LA%20PELICULA%20.pdf)

**Comment by ClaudiaHernandez03** [comment]
Buenas noches Ing, le envió mi tarea
[Tarea 6.2: Comentarios película "The Imitation Game"](https://github.com/ClaudiaHernandez03/automatas/blob/main/Tema%206/Tarea%206.2.md)
_Att. Claudia América Hernández Jiménez_
N°Control: 21200607

**Comment by sergiotorr** [comment]
Buenas tardes profesor hago entrega de la tarea [6.2 Comentario película The Imitation Game](https://github.com/sergiotorr/RepSergio/blob/main/6.2%20Comentario%20pel%C3%ADcula%20The%20Imitation%20Game.pdf)
Torres Martínez Sergio Enrique
No. Boleta: 21200636

**Comment by DonovanFranco** [comment]
Buenas noches ingeniero, envió evidencia de la Actividad 6.2
- [Tarea 6.2](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades%20Tema%206/Tarea%206.2.md)

Por su atención, muchas gracias.
- ***Donovan Urazh Franco Flores***
- **21200596**

**Comment by Jhonny-Gonzalez** [comment]
Buenas noches, hago entrega de la tarea 6.2:
[6.2 Comentarios película "The Imitation Game"](https://github.com/Jhonny-Gonzalez/repositorioNuevo/blob/main/U6/The%20Imitation%20Game.pdf)
Ochoa Gonzalez Jonathan Emir
N.Control: 21200988

**Comment by AlfredoVelazquez** [comment]
Adjunto la actividad correspondiente
[6.2 COMENTARIOS DE LA PELICULA](https://github.com/AlfredoVelazquez/AutoNuevo/blob/main/6.2%20Codigo%20Enigma.pdf)

**Comment by lHatHamy** [comment]
Buenas noches profesor, hago entrega de la [Tarea 6.2.](https://github.com/lHatHamy/lye/blob/main/Tema6/Tarea%206.2.pdf)

Sin mas que agregar por el momento, agradezco su atención durante el curso y su esfuerzo por hacer de la materia interesante, realmente aprendí conceptos que me serán de utilidad para proyectos personales. Le deseo una bonita noche.

> Serrano González Uriel Alberto
> 21200630

**Comment by CariciasDealer** [comment]
Buenas noches, ingeniero. Le hago entrega de la [actividad 6.2](https://github.com/CariciasDealer/Lenguaje-y-Automatas/blob/main/Tema%206/21200631%20-%206.2%20Comentarios%20película%20The%20Imitation%20Game.pdf)

Que pase una excelente noche y muchas gracias por compartir su conocimiento con nosotros. 

Alumno: Taboada Hernandez Erwin Omar
No. Control: 21200631

**Comment by Itzel-Paola-Garcia** [comment]
Actividad subida

**Comment by JohannaMontana** [comment]
Buenos días profesor, le envío la actividad propuesta el día de hoy, para su posterior evaluación

> [Tarea 6.2](https://github.com/JohannaMontana/Lenguajes-Automatas-I/blob/main/Tema%206/6.2_Pelicula_21200619_.pdf)

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._

**Comment by diegoquintos** [comment]
Realizo la entrega de la  [Tarea 6.2](https://github.com/diegoquintos/LengAutomatas/blob/main/Tarea%206.2.pdf)
_Quintos Cabeza Diego, 21200625_
