### ISSUE TITLE
Tarea 1.2. Fases de un compilador

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#2]
Realizar un mapa conceptual de las fases de un compilador.

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 1.2 _Fases de un compilador_
Buenas Tardes profesor le envió el link de mi [Repositorio](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) y mi trabajo.
Link de la tarea:[Tarea 1.2](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/76c3b467522405b1095447d88b5fce0117c48749/Tema%201/1.2.%20Fases%20de%20un%20compilad.md)
Atte. Martin Feria Vázquez NC 21200594

**Comment by Jhonny-Gonzalez** [comment]
Buenas noches, hago entrega de la tarea 1.2
Ochoa Gonzalez Jonathan Emir
N.C: 21200988
[Tarea 1.2](https://github.com/Jhonny-Gonzalez/repositorioNuevo/blob/main/U1/Fases%20de%20un%20compilador.pdf)

**Comment by GermanZL** [comment]
Buen día, le hago entrega de la tarea 1.2.
Link de tarea: [Tarea 1.2 - Zeron Lopez German Eduardo](https://github.com/GermanZL/automatas/blob/master/Tareas/Tarea%201.2.pdf)
Saludos.

**Comment by RDGKing** [comment]
Buen dia, profesor.
Le envío el enlace del apartado donde se encuentra mí tarea:  [**#Tarea 1.2**](https://github.com/RDGKing/Leng.-Y-Automatas-I/blob/main/Tema%201/21200581%20-%20Tarea%201.2.%20Fases%20de%20un%20compilador.pdf)
Y  nuevamente comparto el enlace de mi repositorio donde estaré subiendo mís tareas: [**Repositorio**](https://github.com/RDGKing/Leng.-Y-Automatas-I.git)
Agradezco mucho su atención.

**Comment by UrielAhumada** [comment]
Buen día, entrego tarea 1.2
[Tarea 1.2. Fases de un compilador](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/4add8228c6447f44eacb0f4ab01d7707a4254141/Tema1/Tarea%201.2.pdf)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by PZ222** [comment]
Buen día, profesor.
Le envío el enlace de mi tarea: 
[Tarea 1.2](https://github.com/PZ222/Lenguajes_y_Automatas_Manin/blob/cfaa0fad750220b879f242625460079cc4a67da1/Tema%201/1.2.%20Fases%20de%20un%20compilador.pdf)
Jorge Rafael Garcia Sandoval
N.C: 21200601
Un Saludo.

**Comment by MielFigueroa** [comment]
Buen día, le hago entrega de la tarea 1.2.
No.Control:22200181
 [tarea 1.2:](https://github.com/MielFigueroa/Miel/blob/master/TEMA%201.2.png)
Saludos.

**Comment by GabrielRoFe** [comment]
Buenas tardes, le envío los enlaces a mi repositorio y a la tarea 1.2
_REPOSITORIO_
[Repositorio](https://github.com/GabrielRoFe/LenguajesYAutomatas)
_TAREA 1.2_
[Tarea1.2](https://github.com/GabrielRoFe/LenguajesYAutomatas/blob/37692bb2db6d53bb68fd1351c46ef77168dd4a05/FASES%20DE%20UN%20COMPILADOR.pdf)

**Comment by Josuerh20** [comment]
Buenas tardes le envió la tarea 1.2
Josue Ramírez Hernández 
Link de tarea: [Tarea 1.2](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas/Tarea%201.2%20Josue%20Ramirez%20Hdz.pdf)

**Comment by Itzel-Paola-Garcia** [comment]
Buenas tardes, le envio la tarea 1.2 y el enlace de mi repostorio
Itzel Paola García Lugo
21200599

- [Tarea 1.2](https://github.com/Itzel-Paola-Garcia/LeguajesAutomatas/blob/main/Fases%20de%20un%20compilador.pdfl)
- [Repositorio](https://github.com/Itzel-Paola-Garcia/LeguajesAutomatas)

**Comment by jesus-borja** [comment]
Buenas noches, profesor.
Anexo el enlace a la [Tarea 1.2](https://github.com/jesus-borja/LengAutomatasI/blob/main/Tema%201/Tarea%201.2%20Fases%20de%20un%20Compilador.pdf)

> Jesús Borja Hernández
> No. de Control 21200584

**Comment by DonovanFranco** [comment]
Buenas noches ingeniero, envió evidencia de la Actividad 1.2
- [Tarea 1.2 Fases de un compilador](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades/Tarea%201.2%20Fases%20de%20un%20compilador.pdf)

Por su atención, muchas gracias.
- ***Donovan Urazh Franco Flores***
- **21200596**

**Comment by JohannaMontana** [comment]
Buenas noches profesor, le envío la actividad propuesta el día de hoy, para su posterior evaluación

> [Tarea 1.2 mapa conceptual acerca del compilador](https://github.com/JohannaMontana/Lenguajes-Automatas-I/blob/534e9acbc794f458948bcd98e95f9200c364f2ae/Tema%201/1.2_Fases_compilador.pdf )

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._

**Comment by sergiotorr** [comment]
Buenas noches, hago entrega de la tarea 1.2
Torres Martínez Sergio Enrique
N.C: 21200636
[TAREA 1.2](https://github.com/sergiotorr/RepSergio/blob/main/Fases%20de%20un%20compilador.pdf)

**Comment by Tesla9750** [comment]
## Tarea 1.2. Fases de un compilador

Buenas noches ingeniero,

He realizado la Tarea 1.2 sobre las Fases de un compilador. Adjunto el enlace al documento con mi actividad correspondiente: [Tarea 1.2 - Fases de un compilador](https://github.com/Tesla9750/Lenguajes_y_Automatas_1/blob/7e1b66de89355603b27c9d68f1dad6127f4f49e0/Tema%201/Tarea_1_2_Fases_de_un_compilador.pdf)

Esperando que tenga una grata noche.

_Saludos,_
_Benitez Nava Juan de Dios
Número de control: 21200582
Instituto Tecnológico de Pachuca_

-NOTA: Actualice el link de la actividad debido a que realice cambios dentro de mi repositorio para ubicar mis archivos de manera mas ordenada_

**Comment by lHatHamy** [comment]
Buenas noches estimado profesor.

Mediante este comentario anexo evidencia de la tarea 1.2: **_"Fases de un compilador"._**  Sin mas que añadir por el momento, espero que pase una buena noche y de antemano agradezco su atención.

[Tarea 1.2](https://github.com/lHatHamy/lye/blob/main/Tema1/Tarea1.2.png)

> Serrano González Uriel Alberto
> 21200630

**Comment by GavicGH** [comment]
Hola Profesor, buenas noches. 
Hago entrega de la [Tarea 1.2](https://github.com/VGabriel31/Lenguajes_Automatas_1/blob/main/Tarea%201.2.pdf)

Gracias por su atencion.

> Gutierrez Hernandez Victor Gabriel
> 21200605

**Comment by Marr1731** [comment]
Buenas noches profesor
comparto con usted mi tarea:
[Tarea 1.2](https://github.com/Marr1731/ActividadesLenguajesAutonomas/blob/main/Fases%20del%20compilador.pdf) 

Mendoza Gutiérrez Mariana
21200615

**Comment by CariciasDealer** [comment]
Muy buenas noches, ingeniero. Por este medio le hago entrega de la [actividad 1.2](https://github.com/CariciasDealer/Lenguaje-y-Automatas/blob/main/Tema1/1.2.%20Fases%20de%20un%20compilador%20-%2021200631.png) solicitada. 

¡Que tenga una excelente semana!

Alumno: Taboada Hernandez Erwin Omar
No. Control: 21200631

**Comment by DanielFloresBautista** [comment]
Buenas tardes le envió la [tarea 1.2](https://github.com/DanielFloresBautista/Tarea1.2/blob/main/MAPA%20COMCEPTUAL.pdf)
Flores Bautista Daniel

**Comment by diegoquintos** [comment]
Buenas noches, le comparto la actividad 1.2:
[Tarea 1.2](https://github.com/diegoquintos/LengAutomatas/blob/main/Tarea%201.2.pdf)
Buena semana, hasta luego.

Alumno: Quintos Cabeza Diego 
NC:21200625

**Comment by Marly-R** [comment]
Buenas noches inge. Le hago entrega de la tarea 1.2

[Tema 1.2](https://github.com/Marly-R/RepoNuevo/blob/master/Tema1/Tema%201.2%20Mapa%20conseptual%20fases%20de%20compilador.pdf)

Marly Galarza Acosta 
NC: 22201111

**Comment by Reyes-Hernandez-Reyes** [comment]
Buenas noches profesor
comparto con usted mi tarea:
[Tarea 1.2](https://github.com/Reyes-Hernandez-Reyes/Tarea-1.1/blob/main/Tarea1.2.pdf)

Hernandez Reyes Reyes
21200608

**Comment by abisaiCM** [comment]
AQUI ESTA LA TAREA 1.2 https://github.com/abisaiCM/lenguajesYAutomatas/blob/main/1_2%20FASES%20DE%20UN%20COMPILADOR.pdf

LINDO DIA

**Comment by ClaudiaHernandez03** [comment]
Muy buenas noches, ingeniero. Adjunto mi enlace
[Actividad 1.2](https://github.com/ClaudiaHernandez03/automatas/blob/main/Tema.1/Tarea%201.2.md)

Hernández Jiménez Claudia América
No. Control: 21200607

¡Saludos!
