### ISSUE TITLE
Tarea 2.1. Expresiones Regulares

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#6]
Investigar que es una Expresión Regular, cuál es su importancia y casos de uso.

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 2.1. Expresiones Regulares
Buenas Tardes profesor le envió el link de mi [Repositorio](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) y mi trabajo.
Link de la tarea:[Tarea 2.1](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/1d9461f1a318675a0d3e84d6ea1c46dd0e29a7b3/Tema%202/Tarea%202.1.%20Expresiones%20Regulares.md)
Atte. Martin Feria Vázquez NC 21200594

**Comment by Marly-R** [comment]
Buenas tardes profesor, le hago entrega de mi tarea 2.1  Expresiones Regulares
[Link Tarea 2.1](https://github.com/Marly-R/RepoNuevo/blob/master/Tema2/Tarea%202.1.pdf)
**Alumna:** Marly Galarza Acosta 
**No. Control:**  22201111

**Comment by AdrianSanBad** [comment]
Entregado en la carpeta correspondiente.
https://adriansanbad.github.io/lenguajesAutomatas/

**Comment by DanielFloresBautista** [comment]
Le hago entrega de mi tarea 2.1 Expresiones Regulares
[Link Tarea 2.1](https://github.com/DanielFloresBautista/Unidad2/blob/main/EXPRESI%C3%93N%20REGULAR.pdf)
Nombre: Flores Bautista Daniel
NC: 21200595

**Comment by UrielAhumada** [comment]
Buen día, entrego tarea 2.1
[Tarea 2.1. Expresiones Regulares](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema2/Tarea2.1.md)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by PZ222** [comment]
Buen día, profesor.
Le envío el enlace de mi tarea:
[Tarea 2.1](https://github.com/PZ222/Lenguajes_y_Automatas_Manin/blob/6a552e238a00669b055c5e93bbd258d760fc232f/Tema%202/2.1%20Expresiones%20Regulares.pdf)
Jorge Rafael Garcia Sandoval
N.C: 21200601
Un Saludo.

**Comment by abisaiCM** [comment]
TRAEA DE EXPRECIONES REGULARES
BONITA NOCHE

https://github.com/abisaiCM/lenguajesYAutomatas/blob/main/2.1%20EXPRECIONES%20REGULARES.pdf

**Comment by GermanZL** [comment]
Buen día, le hago entrega del link de la tarea 2.1.
Link de tarea: [Tarea 2.1 - Zeron Lopez German Eduardo](https://github.com/GermanZL/automatas/blob/master/Tareas/Tarea%202.1.%20Expresiones%20Regulares.pdf)
Saludos.

**Comment by Josuerh20** [comment]
Buen día le hago entrega de la Tarea 2.1. Expresiones Regulares
Link de tarea:  [Tarea 2.1 Josue Ramirez Hernandez](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas/Tarea%202.1.%20Expresiones%20Regulares%20JOSUE.pdf)
link de repositorio: [Repositorio](https://github.com/Josuerh20/Lenguajes-Automatas-J)

**Comment by GabrielRoFe** [comment]
Buena tarde, le dejo los enlaces a mi repositorio y a la tarea 2.1:
[REPOSITORIO](https://github.com/GabrielRoFe/LenguajesYAutomatas)
[TAREA 2.1](https://github.com/GabrielRoFe/LenguajesYAutomatas/blob/c249c1a71ecce503d61b78094dcc0662f53873e3/EXPRESI%C3%93N%20REGULAR.md)

**Comment by Majin0328** [comment]
Buenas tardes, anexo mi tarea, recomiendo que baje al zoom al 90% ya que por algun motivo se deforma la imagen en algunos navegadores.

https://majin0328.github.io/LeneguajesAutomatas/

**Comment by DonovanFranco** [comment]
Buenas noches ingeniero, envió evidencia de la Actividad 2.1
- [Tarea 2.1 Expresiones Regulares](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades/Tarea%202.1%20Expresiones%20Regulares.pdf)

Por su atención, muchas gracias.
- ***Donovan Urazh Franco Flores***
- **21200596**

**Comment by sergiotorr** [comment]
Buenas noches profesor, anexo mi tarea [Tarea 2.1](https://github.com/sergiotorr/RepSergio/blob/main/Expresi%C3%B3n%20Regular_21200636.pdf)
Alumno: Torres Martínez Sergio Enrique
Boleta: 21200636

**Comment by GavicGH** [comment]
Buenas noches profesor
comparto mi tarea del tema 2 : [Tarea 2.1](https://github.com/VGabriel31/Lenguajes_Automatas_1/blob/main/Expresiones%20Regulares%20.pdf)

Gutiérrez Hernández Victor Gabriel
21200605

**Comment by Marr1731** [comment]
Buenas noches profesor
Hago entrega de mi tarea del tema 2 : [Tarea 2.1](https://github.com/Marr1731/ActividadesLenguajesAutonomas/blob/main/Expresiones%20Regulares%20.pdf)



Mendoza Gutiérrez Mariana 
21200615

**Comment by Jhonny-Gonzalez** [comment]
Buenas noches, hago entrega de la tarea 2.1:
[Tarea 2.1. Expresiones Regulares](https://github.com/Jhonny-Gonzalez/repositorioNuevo/blob/main/U2/Tarea%202.1.%20Expresiones%20Regulares.pdf)
Ochoa Gonzalez Jonathan Emir
N.Control: 21200988

**Comment by AlfredoVelazquez** [comment]
BUENAS NOCHES ING, HAGO ENTREGA DE MI TAREA 2.21
[TAREA 2.1](https://github.com/AlfredoVelazquez/AutoNuevo/blob/main/2.1%20Expresiones%20Regulares.pdf)
José Alfredo Velázquez León
21200240

**Comment by Tesla9750** [comment]
## Tarea 2.1. Expresiones Regulares

Buenas noches ingeniero,

Adjunto el enlace al documento donde he completado la [Tarea 2.1. Expresiones Regulares](https://github.com/Tesla9750/Lenguajes_y_Automatas_1/blob/7683714e9d1aeb1c63a817dc86c360f43b19909c/Tema%202/Tarea_2_1_Expresiones_Regulares.md)

Esperando que cuente con una grata noche, me despido. 

Saludos,

*Benitez Nava Juan de Dios
Número de control: 21200582
Instituto Tecnológico de Pachuca*

**Comment by JohannaMontana** [comment]
Buenas noches profesor, le envío la actividad propuesta el día de hoy, para su posterior evaluación

> [Tarea 2.1. Expresiones Regulares](https://github.com/JohannaMontana/Lenguajes-Automatas-I/blob/main/Tema%202/2.1_Expresiones_Regulares.pdf)

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._

**Comment by diegoquintos** [comment]
Hola buenas noches, le anexo la tarea 2.1
[Tarea 2.1](https://github.com/diegoquintos/LengAutomatas/blob/main/ExpresionesRegulares.pdf)
Excelente noche.  
_Quintos Cabeza Diego-21200625_

**Comment by lHatHamy** [comment]
**_Buenas noches estimado profesor_**

deseando que tenga una grata noche, hago entrega de mi evidencia de la tarea 2.1 en mi repositorio personal. Sin más que agregar por el momento, deseo que pase un excelente día.

[Tarea 2.1](https://github.com/lHatHamy/lye/blob/main/Tema2/Tarea2_1.pdf)

> Serrano González Uriel Alberto
> 21200630

**Comment by MielFigueroa** [comment]
Entrega de la Tarea 2.1. Expresiones Regulares
Buenas Noches profesor le envió el link de mi [repositorio](https://github.com/MielFigueroa/Miel.git) 
Link de la tarea: [Tarea 2.1](https://github.com/MielFigueroa/Miel/blob/master/Tema%202.1.pdf)
Atte: Melanie Dominguez Figueroa    No. Control: 22200181

**Comment by Reyes-Hernandez-Reyes** [comment]
Buenas noches profesor. Le Adjunto enlace del la [Tarea 2.1](https://github.com/Reyes-Hernandez-Reyes/Tareas-Tema-2/blob/main/Tarea%202.1.pdf) del Tema numero 2
Alumno: Hernandez Reyes Reyes
No.Control: 21200608

**Comment by MaRqKiTe** [comment]
Entrega de la [Tarea 2.1](https://github.com/MaRqKiTe/repe/tree/master/Tema%202) Expresiones Regulares

 Lara López Marco Antonio No. Control: 22200191

**Comment by CariciasDealer** [comment]
Buenas noches, ingeniero. Le hago entrega de la [actividad 2.1](https://github.com/CariciasDealer/Lenguaje-y-Automatas/blob/main/Tema%202/21200631%20-%202.1%20Expresiones%20Regulares.pdf) que se solicito.
¡Que tenga una excelente semana!

Alumno: Taboada Hernandez Erwin Omar
No. Control: 21200631

**Comment by jesus-borja** [comment]
Buenas noches, profesor.
Anexo el enlace a mi entrega de la [Tarea 2.1](https://github.com/jesus-borja/LengAutomatasI/blob/main/Tema%202/Tarea%202.1%20Expresiones%20Regulares.pdf)

> Jesús Borja Hernández
> No. de Control: 21200584

**Comment by AriMC432** [comment]
Buenas noches profesor, le anexo en link de la tarea 1 de la unidad 2:
https://github.com/AriMC432/Repts/blob/master/Tareas/U2_T1_Expresiones%20Regulares.pdf

Gracias. 

Ariana Muñoz Castillo 22-200-196

**Comment by ClaudiaHernandez03** [comment]
Muy buenas noches, ingeniero. Adjunto mi enlace
[Actividad 2.1](https://github.com/ClaudiaHernandez03/automatas/blob/main/Tema%202/Actividad%202.1.md)

Hernández Jiménez Claudia América
No. Control: 21200607

¡Saludos!
