### ISSUE TITLE
Tarea 2.2

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#7]
Después de haber realizado sus practicas con el ejemplo de expresiones regulares y como crear un bot en telegram, crear un hibrido de las dos practicas y modificar su bot de telegram e implementar alguna de las preguntas u opciones que tienen en el ejemplo de expresiones regulares (De preferencia crear una nueva expresión regular propuesta por ustedes).

Deben publicar su código en GitHub y documentar en el Readme con pantallas del resultado del bot.

**Comment by PZ222** [comment]
Buen día, profesor.
Le envío el enlace de mi tarea:
[Tarea 2.2](https://github.com/PZ222/Lenguajes_y_Automatas_Manin/tree/9001876a2589e8150957e10cdd9672374085c180/Tema%202/Tarea%202.2)
Jorge Rafael Garcia Sandoval
N.C: 21200601
Un Saludo.

**Comment by jesus-borja** [comment]
Buenas noches, profesor.
Anexo el enlace a mi entrega de la [Tarea 2.2](https://github.com/jesus-borja/LengAutomatasI/tree/main/Tema%202/Tarea%202.2%20bot-regex-telegram)

> Jesús Borja Hernández
> No. de Control: 21200584

**Comment by Jhonny-Gonzalez** [comment]
Buenas noches, hago entrega de la tarea 2.2:
[Tarea 2.2.](https://github.com/Jhonny-Gonzalez/repositorioNuevo/tree/Tarea-2.2)
Ochoa Gonzalez Jonathan Emir
N.Control: 21200988

**Comment by Josuerh20** [comment]
Buenas noches, le hago entrega de la tarea 2.2
[Tarea 2.2](https://github.com/Josuerh20/Lenguajes-Automatas-J/tree/master/Tareas%20Tema%202/Tarea%202.2)

Josue Ramirez Hernández
21200990

**Comment by AdrianSanBad** [comment]
🚀 realizado

**Comment by GermanZL** [comment]
Buenas noches, le hago entrega de la tarea 2.2
[Tarea 2.2](https://github.com/GermanZL/automatas/tree/master/Tareas/Tarea%202.2)

Zeron Lopez German Eduardo
21200642

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 2.2. Expresiones Regulares
Buenas Tardes profesor le envió el link de mi [Repositorio](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) y mi trabajo.
Link de la tarea:[Tarea 2.2](https://github.com/MartinFV-001/BotTelegram)
Atte. Martin Feria Vázquez NC 21200594

**Comment by Tesla9750** [comment]
## # Tarea 2.2 . Expresiones Regulares mediante Telegram

Buenas noches ingeniero,

Adjunto el enlace al documento donde he completado la [#Tarea 2.2 ](https://github.com/Tesla9750/Lenguajes_y_Automatas_1/tree/22cbd53a28a545b2407c0d07e2768a3a3aa41756/Tema%202/Tarea%202_2%20Expresiones%20Regulares%20Con%20Telegram)

Esperando que cuente con una grata noche, me despido. 

Saludos,

*Benitez Nava Juan de Dios
Número de control: 21200582
Instituto Tecnológico de Pachuca*

**Comment by GabrielRoFe** [comment]
Buenos días, entrego la tarea 2.2

[TAREA 2.2](https://github.com/GabrielRoFe/LenguajesYAutomatas/blob/main/Tarea%202.2.md)
Vera Rodríguez Héctor Gabriel
21200640

**Comment by JAEP-22** [comment]
.

**Comment by DanielFloresBautista** [comment]
Entrega de la Tarea 2.2. Expresiones Regulares

Link de la tarea: [Tarea 2.2](https://github.com/DanielFloresBautista/Unidad2/blob/main/TAREA%202.pdf)
Nombre: Flores Bautista Daniel NC 21200595

**Comment by lHatHamy** [comment]
Buenas noches profesor.

Anexo evidencia de mi practica de la [tarea 2.2](https://github.com/lHatHamy/lye/tree/main/Tema2/Tarea2.2). En esta carpeta se encontrará un pequeño reporte de practica y el respectivo codigo.

Sin mas que agregar por el momento, le agradezco de antemano y le deseo una bonita noche.

> Serrano González Uriel Alberto

> 21200630

**Comment by Marly-R** [comment]
Buenas noches profesor, le hago entrega de mi tarea 2.2
[Tarea 2.2](https://github.com/Marly-R/RepoNuevo/tree/master/Tema2/Tema2.2)
Marly Galarza Acosta 
Numero de control: 22201111

**Comment by Yess0222** [comment]
Buenas noches, envio la tarea 2.2 
[Tarea 2.2](https://github.com/Yess0222/Lenguajes-/blob/master/Tarea%202.2.md)
Yesenia Morales Ordoñez 22200348

**Comment by JAEP-22** [comment]
Buenas noches profresor 
Adjunto mi tarea 2.2 del bot
Jose Pablo Martinez Gonzalez 
NC:  22200194
[Tarea 2.2](https://github.com/JAEP-22/Yesenia/blob/master/TAREA%202.2%20README.md)

**Comment by JohannaMontana** [comment]
Buenas noches profesor, le envío la actividad propuesta el día de hoy, para su posterior evaluación

> [Tarea 2.2](https://github.com/JohannaMontana/Lenguajes-Automatas-I/tree/main/Tema%202/TelegramBot)

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._

**Comment by sergiotorr** [comment]
Buenas noches profesor, le hago entrega de mi tarea 2.2
[Tarea 2.2](https://github.com/sergiotorr/RepSergio/blob/main/README.md)
Torres Martínez Sergio Enrique
No. Boleta: 21200636

**Comment by ClaudiaHernandez03** [comment]
Buenos días, entrego la tarea 2.2

[TAREA 2.2](https://github.com/ClaudiaHernandez03/automatas/tree/main/Tema%202/Tarea%202.2)
Claudia América Hernández Jiménez
21200607

**Comment by Reyes-Hernandez-Reyes** [comment]
Buenas noches profesor, le hago entrega de la Tarea 2.2
[Tarea 2.2](https://github.com/Reyes-Hernandez-Reyes/Tareas-Tema-2/blob/main/Tarea%202.2.md)
Hernandez Reyes Reyes
No. Control: 21200608

**Comment by CariciasDealer** [comment]
Buenas noches, ingeniero. Le hago entrega de la [tarea 2.2](https://github.com/CariciasDealer/Lenguaje-y-Automatas/tree/main/Tema%202/Tema%202.2) para evaluar esta unidad.

¡Que tenga una excelente semana!
Taboada Hernandez Erwin Omar
No. Control: 21200631

**Comment by MaRqKiTe** [comment]
Buenas noches 
Adjunto evidencia de la [tarea 2.2](https://github.com/MaRqKiTe/repe/blob/master/Tema%202/readme.md) del bot
Lara López Marco Antonio 
No. Control: 22200191

**Comment by AriMC432** [comment]
Buenas noches
https://github.com/AriMC432/Repts/blob/master/Tareas/2.2%20Bot.pdf lin de mi reporte del bot

Ariana Muñoz Castillo 22200196

Gracias

**Comment by DonovanFranco** [comment]
Buenas noches ingeniero, envió evidencia de la Actividad 2.2
- [Tarea 2.2](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades%20Tema%202/Tarea%202.2.md)

Por su atención, muchas gracias.
- ***Donovan Urazh Franco Flores***
- **21200596**

**Comment by UrielAhumada** [comment]
Buen día, entrego tarea 2.2
[Tarea 2.2](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema2/Tarea2.2.md)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by GavicGH** [comment]
Hola profesor, buenas noches, una disculpa por la demora de verdad, pero aqui le hago entrega de mi repositorio, 

https://github.com/VGabriel31/Lenguajes_Automatas_1

**Comment by AlfredoVelazquez** [comment]
[REPORSITORIO SOBRE EXPRESIONES REGULARES] "PRÁCTICA DE BOT"
(https://github.com/AlfredoVelazquez/ExpresionesReg)

**Comment by AlfredoVelazquez** [comment]
Ing. Disculpando la demora, nuevamente me presento fallas mi bot, pero al fin pude solucionarlo. En el repositorio esta lo correspondiente a la práctica. Gracias
[REPOSITORIO DE EXPRESIONES REGULARES](https://github.com/AlfredoVelazquez/ExpresionesReg)

**Comment by DanielFloresBautista** [comment]
Entrega de la Tarea 2.2. 

Link de la tarea: [Tarea 2.2](https://github.com/DanielFloresBautista/Unidad2/blob/main/Bot.md)
Nombre: Flores Bautista Daniel NC 21200595

**Comment by diegoquintos** [comment]
Realizo la entrega de la [Tarea 2.2](https://github.com/diegoquintos/LengAutomatas/blob/main/Tarea2_2.md)
_Quintos Cabeza Diego-21200625_
