### ISSUE TITLE
Tarea 2.3

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#8]
Expresión regular que valide un **Password** fuerte
1 minúscula
1 mayúscula
1 numero
1 carácter especial
8 caracteres de longitud

Expresión Regular que valide un **Nombre de usuario**
Longitud de 3 a 16 caracteres
Letra o numero o guion medio o bajo

**Comment by PZ222** [comment]
Buen día, profesor.
Le envío el enlace de mi tarea:
[Tarea 2.3](https://github.com/PZ222/Lenguajes_y_Automatas_Manin/blob/d4188d299df9af0480f1d3ca3cb3172ca282fd4b/Tema%202/Tarea%202_3.md)
Jorge Rafael Garcia Sandoval
N.C: 21200601
Un Saludo.

**Comment by Josuerh20** [comment]
Buenas tardes le hago entrega de la tarea 2.3
[Tarea 2.3 Josue](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas%20Tema%202/Tarea%202.3.md)

Josue Ramirez Hernandez 21200990

**Comment by GabrielRoFe** [comment]
Buena tarde, entrego la tarea 2.3

[Tarea 2.3 VRHG](https://github.com/GabrielRoFe/LenguajesYAutomatas/blob/main/Tarea%202.3.md)

Vera Rodríguez Héctor Gabriel
21200640

**Comment by GermanZL** [comment]
Buenas tardes le hago entrega de la tarea 2.3
[Tarea 2.3](https://github.com/GermanZL/automatas/blob/master/Tareas/tarea%202.3.md)

Zeron Lopez German Eduardo - 21200642

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 2.3 Expreciones Regulares Password
Buenas Tardes profesor le envió el link de mi [Repositorio](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) y mi trabajo.
Link de la tarea:[Tarea 2.3](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/8631072e464a1481559e7ce11a02780ba6290319/Tema%202/2.3%20Password_Fuerte.md)
Atte. Martin Feria Vázquez NC 21200594

**Comment by Jhonny-Gonzalez** [comment]
Buenas noches, hago entrega de la tarea 2.3:
[Tarea 2.3.](https://github.com/Jhonny-Gonzalez/repositorioNuevo/blob/main/U2/README.md)
Ochoa Gonzalez Jonathan Emir
N.Control: 21200988

**Comment by Marly-R** [comment]
Buenas noches profesor, le hago entrega de la tarea 2.3:
[Tarea 2.3.](https://github.com/Marly-R/RepoNuevo/blob/master/Tema2/tarea2.3.md)
Galarza Acosta Marly 
N.Control: 22201111

**Comment by UrielAhumada** [comment]
Buen día, entrego tarea 2.3
[Tarea 2.3 ](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema2/Tarea2.3.md)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by MielFigueroa** [comment]
Buenas tardes, entrego la tarea 2.3
[TAREA2.3](https://github.com/MielFigueroa/Miel/blob/master/TAREA%202.3.pdf)
No. Control 22200181

**Comment by AlfredoVelazquez** [comment]
Buenas noches Ing. Adjunto la tarea correspondiente!
José Alfredo Velázquez
[Tarea 2.3](https://github.com/AlfredoVelazquez/AutoNuevo/blob/main/Tarea%202.3.pdf)

**Comment by AriMC432** [comment]
Buenas noches profesor, hago entrega de la tarea
Tarea 2.3 https://github.com/AriMC432/Repts/blob/master/Tareas/Tarea%202.3.pdf
Ariana Muñoz Castillo 
No° Control 22 - 200 - 196

**Comment by DonovanFranco** [comment]
Buenas noches ingeniero, envió evidencia de la Actividad 2.3
- [Tarea 2.3](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades%20Tema%202/Tarea%202.3.md)

Por su atención, muchas gracias.
- ***Donovan Urazh Franco Flores***
- **21200596**

**Comment by Yess0222** [comment]
Buenas noches envio la tarea 2.3
[Tarea 2.3](https://github.com/Yess0222/Lenguajes-/blob/master/Tarea%202.3.md)
Yesenia Morales Ordoñez 22200348

**Comment by AdrianSanBad** [comment]
entregada en el repositorio correspondiente 🚀

**Comment by Tesla9750** [comment]
## # Tarea 2.3  Ejercicios de Practica

Buenas noches ingeniero,

Adjunto el enlace al documento donde he completado la [#Tarea 2.3 ](https://github.com/Tesla9750/Lenguajes_y_Automatas_1/blob/395c5d451bec3ac17fa85422a7acc8f11a687e06/Tema%202/Tarea_2_3_Ejercicos_expresiones_regulares.md)

Esperando que cuente con una grata noche, me despido. 

Saludos,

*Benitez Nava Juan de Dios
Número de control: 21200582
Instituto Tecnológico de Pachuca*

**Comment by JAEP-22** [comment]
Adjunto mi tarea
[Tarea 2.3](https://github.com/JAEP-22/Yesenia/blob/master/Tarea%202.3.md)
Jose Pablo Martinez Gonzalez 
22200194

**Comment by JohannaMontana** [comment]
Buenas noches profesor, le envío la actividad propuesta para el día de hoy, para su posterior evaluación

> [Tarea 2.3](https://github.com/JohannaMontana/Lenguajes-Automatas-I/blob/main/Tema%202/2.3_Expresiones.pdf)

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._

**Comment by ClaudiaHernandez03** [comment]
Buenas noches, hago entrega de la tarea 2.3:
[Tarea 2.3.](https://github.com/ClaudiaHernandez03/automatas/blob/main/Tema%202/Tarea%202.3.md)
Claudia América Hernández Jiménez 
N.Control: 21200607

**Comment by diegoquintos** [comment]
Buenas noches profesor, le anexo la [Tarea 2.3](https://github.com/diegoquintos/LengAutomatas/blob/main/tarea_2.3.md)
Gracias.
Quintos Cabeza Diego-21200625

**Comment by MaRqKiTe** [comment]
Entrega de la evidencia actividad [tarea 2.3](https://github.com/MaRqKiTe/repe/blob/master/Tema%202/readme2.md)
Lara López Marco Antonio
No. Control: 22200191
