### ISSUE TITLE
Tarea 3.1 Ejercicios AFN

### ISSUE THREAD

**Issue by RodolfoBaume** [RodolfoBaume/LenguajesAutomatas#9]
Realizar los ejercicios acordados en clase de la **página 49**, del libro **Teoría de la computación de Carrión Viramontes**

**Comment by MartinFV-001** [comment]
Entrega de la Tarea 3.1 Ejercicios AFN
Buenas Tardes profesor le envió el link de mi [Repositorio](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I.git) y mi trabajo.
Link de la tarea: [Tarea 3.1](https://github.com/MartinFV-001/Lenguaje-y-Automtas-I/blob/6137ce6a65f44547ef8bf67d36ba55e80ee91001/Tema%203/3.1%20Ejercicios%20libro.md)
Atte. Martin Feria Vázquez NC 21200594
**El libro que debemos ocupar esta en el apartado de referencias por si aun no lo tienen**
VERSION FINAL 23/04/2024 - 05:17 PM

**Comment by Josuerh20** [comment]
Buenas noches le hago entrega de la tarea 3.1
[Tarea 3.1](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas%20Tema%203/Tarea%203.1%20Ejercicios%20AFN.md)
[Repositorio](https://github.com/Josuerh20/Lenguajes-Automatas-J)
Josue Ramirez Hernández - 21200990

**Comment by GermanZL** [comment]
Buen día le hago entrega de la tarea 3.1
[Tarea 3.1](https://github.com/GermanZL/automatas/blob/master/Tareas/Tarea%203.1.md)
Zeron Lopez German Eduardo - 21200642

**Comment by Josuerh20** [comment]
Buenos días le hago entrega de la tarea 3.1
Link de la tarea [Tarea 3.1](https://github.com/Josuerh20/Lenguajes-Automatas-J/blob/master/Tareas%20Tema%203/Tarea%203.1%20Ejercicios%20AFN.md) 

Josue Ramírez Hernández -21200990

**Comment by GermanZL** [comment]
Buenos días le hago entrega de la tarea 3.1
Link de la tarea [Tarea 3.1](https://github.com/GermanZL/automatas/blob/master/Tareas/Tarea%203.1.md)

Zeron Lopez German Eduardo - 21200642

**Comment by JohannaMontana** [comment]
Buenos días profesor, le envío la actividad propuesta el día de hoy, para su posterior evaluación

> [Tarea 3.1](https://github.com/JohannaMontana/Lenguajes-Automatas-I)

_Morales Mateos Johanna_
_Alumna de ingeniería en sistemas computacionales._
_Matrícula: 21200619_
_Instituto Tecnológico de Pachuca._

**Comment by Marly-R** [comment]
Buenos tardes profesor, le hago entrega de mi tarea 3.1

[Tarea 3.1](https://github.com/Marly-R/RepoNuevo/blob/master/Tema3/Tema%203.1.pdf)

Marly Galarza Acosta
Matrícula: 22201111

**Comment by DonovanFranco** [comment]
Buenas noches ingeniero, envió evidencia de la Actividad 3.1
- [Tarea 3.1](https://github.com/DonovanFranco/Lenguajes_Automatas_1/blob/main/Actividades%20Tema%203/Tarea%203.1.md)

Por su atención, muchas gracias.
- ***Donovan Urazh Franco Flores***
- **21200596**

**Comment by Jhonny-Gonzalez** [comment]
Buenas noches, hago entrega de la tarea 3.1:
[Tarea 3.1 Ejercicios AFN](https://github.com/Jhonny-Gonzalez/repositorioNuevo/blob/main/U3/Tarea%203.1.md)
Ochoa Gonzalez Jonathan Emir
N.Control: 21200988

**Comment by UrielAhumada** [comment]
Buen día, entrego tarea 3.1
[Tarea 3.1. Ejercicios AFN](https://github.com/UrielAhumada/Lenguajes_Automatas1/blob/main/Tema3/Tarea3.1.md)
Att. Uriel Ahumada Huerta
Nc. 21200573

**Comment by AdrianSanBad** [comment]
🚀

**Comment by MielFigueroa** [comment]
Buenas noches profesor 
entrego [TAREA 3.1](https://github.com/MielFigueroa/Miel/blob/master/TAREA%203.1%20correcto.pdf)
Melanie Dominguez Figueroa  No. Control: 22200181

**Comment by Tesla9750** [comment]
##  Tarea 3.1 Ejercicios AFN  #9

Buenas días ingeniero,

Adjunto el enlace al documento donde he completado la [#Tarea 3.1 ](https://github.com/Tesla9750/Lenguajes_y_Automatas_1/blob/003fb39bbfff7806071fbb3d8a5a9aae81f82b81/Tema%203/Tarea_3_2_Automatas_finitos.md)

Esperando que cuente con un grato día, me despido. 

Saludos,

*Benitez Nava Juan de Dios
Número de control: 21200582
Instituto Tecnológico de Pachuca*

**Comment by lHatHamy** [comment]
Buenos días profesor.

Hago entrega de la evidencia de la [Tarea 3.1](https://github.com/lHatHamy/lye/blob/main/Tema3/Tarea3.1.pdf). Sin mas que agregar por el momento le deseo un bonito día.

>Uriel Alberto Serrano González 
>21200630

**Comment by CariciasDealer** [comment]
¡Buenos dias, ingeniero! 
Le hago entrega de la [Tarea 3.1](https://github.com/CariciasDealer/Lenguaje-y-Automatas/blob/main/Tema%203/21200631%20-%20Tarea%203.1%20Ejercicios%20AFN.pdf), que tenga un excelente dia. 

Alumno: Taboada Hernandez Erwin Omar
No. Control: 21200631

**Comment by sergiotorr** [comment]
Buenos dias profesor, hago entrega de la [Tarea 3.1](https://github.com/sergiotorr/RepSergio/blob/main/3.pdf)
Alumno: Torres Martínez Sergio Enrique
No. Boleta: 21200636

**Comment by ClaudiaHernandez03** [comment]
Buenas tardes Ingeniero, le hago entrega de mi tarea 3.1
 
[Tarea 3.1](https://github.com/ClaudiaHernandez03/automatas/blob/main/Tema%203/Tema%203.md)

Claudia América Hernández Jiménez 
Número de control: 21200607

**Comment by DanielFloresBautista** [comment]
Hola buenas tardes, hago entrega de mi tarea 3.1
[Tarea 3.1](https://github.com/DanielFloresBautista/NuevoRepositorio/blob/main/EJERCICIOS.pdf)



Daniel Flores Bautista 21200595

**Comment by Reyes-Hernandez-Reyes** [comment]
Buenas tardes Ingeniero, le hago entrega de la [Tarea 3.1](https://github.com/Reyes-Hernandez-Reyes/Tareas-Tema-3/blob/main/Tarea%203.1.pdf)
Hernandez Reyes Reyes
Número de control: 21200608

**Comment by diegoquintos** [comment]
Buena tarde, hago el envió de la tarea [Tarea 3.1](https://github.com/diegoquintos/LengAutomatas/blob/main/Tarea3.1.pdf)
Quintos Cabeza Diego 
N.C: 21200625

**Comment by AlfredoVelazquez** [comment]
Envio de la Tarea correspondiente.....
[Tarea 3.1](https://github.com/AlfredoVelazquez/AutoNuevo/blob/main/3.1%20Automatas%20Finitos.pdf)

**Comment by belen1909** [comment]
le mando el link de mi [repositorio](https://github.com/belen1909/belenautomatas/blob/main/ACT%20%201%20TEMA%203.pdf)
Belen Barraza Islas 20200181
